{% set name = "skops" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/skops-dev/skops/archive/v{{ version }}.tar.gz
  sha256: c72cea87f45ae85d5d50f4601fcef75038318cb0221398bd31b20666a57f8cd1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - scikit-learn >=1.1
    - huggingface_hub >=0.17.0
    - tabulate >=0.8.8
    - packaging >=17.0

test:
  imports:
    - skops
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A set of tools, related to machine learning in production.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - adrinjalali
