{% set name = "skops" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://github.com/skops-dev/skops/archive/v{{ version }}.tar.gz
  sha256: 6ce9d729bc9ac8be39335e843c091d918b5bd80b18d13924d293c5fd34e9f513

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - setuptools-scm >=10
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.25.0
    - scipy >=1.10.0
    - scikit-learn >=1.2
    - prettytable >=3.9
    - packaging >=17.0

test:
  imports:
    - skops
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/skops-dev/skops
  summary: A set of tools, related to machine learning in production.
  license: MIT
  license_file: LICENSE
  doc_url: http://github.com/skops-dev/skops
  dev_url: http://github.com/skops-dev/skops

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - adrinjalali
