{% set name = "skops" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skops-{{ version }}.tar.gz
  sha256: 2b0bf603c97b7b9956d7a1881b87a63309f2c28d6e4a3ea13d56d4e80ba8b94e

build:
  number: 0
  noarch: python
  # Grayskull generate the following line
  #   skip: true  # [py<37]
  # But we are using "noarch: python" with "python >=3.7"
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - huggingface_hub >=0.8.1
    - modelcards >=0.1.6
    - scikit-learn >=0.24
    - tabulate >=0.8.8
    - typing-extensions >=3.7

test:
  imports:
    - skops
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/skops-dev/skops
  summary: A set of tools to push scikit-learn based models to and pull from Hugging Face Hub
  license: MIT
  license_file:
    - LICENSE
  doc_url: http://github.com/skops-dev/skops
  dev_url: http://github.com/skops-dev/skops

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - adrinjalali
