{% set name = "skops" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skops-{{ version }}.tar.gz
  sha256: 3e39333d65f26d5863ad44db5001b4cfe6a29642274ac37af54fb834813aee3f

build:
  number: 0
  noarch: python
  # Grayskull generate the following line
  #   skip: true  # [py<38]
  # But we are using "noarch: python" with "python >=3.8"
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - huggingface_hub >=0.10.1
    - scikit-learn >=0.24
    - tabulate >=0.8.8

test:
  imports:
    - skops
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/skops-dev/skops
  summary: A set of tools to push scikit-learn based models to and pull from Hugging Face Hub
  license: MIT
  license_file:
    - LICENSE
  doc_url: http://github.com/skops-dev/skops
  dev_url: http://github.com/skops-dev/skops

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - adrinjalali
